### ISSUE TITLE
"invalid pointer on stack" panic

### ISSUE THREAD

**Issue by secDre4mer** [hillu/go-yara#101]
Rarely, go-yara seems to panic with an error message like this:

```
runtime: bad pointer in frame github.com/hillu/go-yara/v4.(*Rules).ScanMem.func1 at 0xc000221a48: 0xb6e
fatal error: invalid pointer found on stack
...
goroutine 282 [running]:
runtime.cgoCheckPointer(0x7ff794ef5ec0, 0xb6e, 0x0, 0x0)
  C:/BuildAgent/work/fde0be651ae9e38/_3rdparty/go/src/runtime/cgocall.go:381 +0x1ab fp=0xc000221a00 sp=0xc0002219f8 pc=0x7ff794395b6b
github.com/hillu/go-yara/v4.(*Rules).ScanMem.func1(0xc000006428, 0xc00008f7d0, 0xc00008f7d0, 0x2f, 0x30, 0x0, 0x7ff79512a980, 0xc0001a1e38, 0xb6e, 0xdf8475800, ...)
  C:/BuildAgent/work/fde0be651ae9e38/vendor/github.com/hillu/go-yara/v4/rules.go:88 +0xc7 fp=0xc000221a70 sp=0xc000221a00 pc=0x7ff7948f6ca7
github.com/hillu/go-yara/v4.(*Rules).ScanMem(0xc000006428, 0xc00008f7d0, 0x2f, 0x30, 0x0, 0xdf8475800, 0x7ff79512a980, 0xc0001a1e38, 0x0, 0x0)
  C:/BuildAgent/work/fde0be651ae9e38/vendor/github.com/hillu/go-yara/v4/rules.go:88 +0x1af fp=0xc000221b00 sp=0xc000221a70 pc=0x7ff7948f13af
...
```

This was probably introduced by my last PR that introduced use of cgo.Handle; apparently, real pointers (like previously generated by the cbpool) are fine, but fake pointers can cause the runtime to panic.

To be compliant, we'd have to do all the (uintptr -> void*) conversions in C, not in Golang. 

@hillu  what is your preferred approach for this? I can add the wrappers for the yara functions / to set the pointer members of C structs if you think that approach is worthwhile. Otherwise, we might want to reconsider a rollback to the cbpool (which is compliant since it uses pointers to an internal array internally).

**Comment by secDre4mer** [comment]
I think `id` would then go out of scope during the cgo call since at that time, Golang doesn't retain any reference to it. Example: id = 3, &id = 0xdeadbeef. The cgo.Handle 3 is retained, but the allocated memory at 0xdeadbeef could be garbage collected, causing undefined behaviour when it is dereferenced.

**Comment by hillu** [comment]
I believe that it would be kept alive in `(*Rules).Scan*` methods, but to be sure, we can sprinkle some `runtime.KeepAlive`. It's different for `Scanner`. I suppose the id needs to be stored in a slot of Scanner that won't be collected or moved. (i.e. allocated using `malloc`).

Do the panics happen with Go 1.18 or also with earlier versions? Are they somehow reproducible?

**Comment by secDre4mer** [comment]
The panics happen with all go versions I've tested with (Go 1.16, 1.17 and 1.18). 

An easy way to reproduce this is:

```
	c, _ := NewCompiler()
	var counter = 0
	defer func() { println(counter) }()
	for counter < 1e9 {
		c.AddString("", "")
		counter++
	}
```

This can also result in a `runtime error: cgo argument has Go pointer to Go pointer` panic.
I like the `malloc` idea: This could also be incorporated in a wrapper around cgo.Handle that automatically `free`s the memory when it is no longer used.

**Comment by secDre4mer** [comment]
Addressed by referenced commit.
