### ISSUE TITLE
Error when compiling go-yara

### ISSUE THREAD

**Issue by rail83** [hillu/go-yara#106]
I'm trying to build a Linux binary using on Go 1.17

The command lines I used:
```
wget https://codeload.github.com/VirusTotal/yara/tar.gz/refs/tags/v4.2.2 -O v4.2.2.tar.gz
tar -zxvf v4.2.2.tar.gz
cd yara-4.2.2/ && ./bootstrap.sh
cd yara-4.2.2/ && ./configure --disable-shared --enable-static --without-crypto
cd yara-4.2.2/ && make && make install
cp /usr/local/lib/pkgconfig/yara.pc /usr/lib/pkgconfig
export YARA_SRC=$PWD/yara-4.2.2
export CGO_CFLAGS="-I${YARA_SRC}/libyara/include"
export CGO_LDFLAGS="-L${YARA_SRC}/libyara/.libs -lyara -lm"
cd project && go get ./...
cd project && go build -o yara_engine
```

Then I get the following errors:
```
# github.com/hillu/go-yara/v4
/usr/local/lib/libyara.a(math.o): In function `string_entropy':
math.c:(.text+0x9ac): undefined reference to `log2'
/usr/local/lib/libyara.a(math.o): In function `data_entropy':
math.c:(.text+0x1132): undefined reference to `log2'
collect2: error: ld returned 1 exit status
```

**Comment by hillu** [comment]
You seem to be conflating several things, cargo-cult style.

Since you seem to be fine with "tainting" your build environment by installing stuff to `/usr` that does not come from packages, try the following:
- pass `--prefix=/usr` to the `configure` run.
- don't copy yara.pc
- don't set `CGO_*` variables.
- Set `-extldflags` as described in the README for static builds.

**Comment by rail83** [comment]
Used the following command lines, I built the Linux binary successfully.
```
wget https://codeload.github.com/VirusTotal/yara/tar.gz/refs/tags/v4.2.2 -O v4.2.2.tar.gz
tar -zxvf v4.2.2.tar.gz
cd yara-4.2.2/ && ./bootstrap.sh
cd yara-4.2.2/ && ./configure --disable-shared --enable-static --without-crypto --prefix=/usr
cd yara-4.2.2/ && make && make install
export YARA_SRC=$PWD/yara-4.2.2
cd project && go env -w GO111MODULE=on && go env && go mod tidy
cd project && go build -ldflags '-extldflags \"-static\"' -tags yara_static -o ../../build/yara_engine
```

Still, I got a warning, is there anything more I should do?
```
# yara
/tmp/go-link-3709544510/000018.o: In function `_cgo_3c1cec0c9a4e_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by hillu** [comment]
> Used the following command lines, I built the Linux binary successfully.

Great.

> Still, I got a warning, is there anything more I should do?

Yeah, here things get more complicated. GNU libc is not intended to be linked statically, particularly name lookups (hostnames, usernames, DNS…) will not work.

If you can live with that, just do a static-only build of YARA as you are doing now and omit the `-extldflags` parameter to `go`.

**Comment by rail83** [comment]
Thank you very much for your help and your awesome projects!
