### ISSUE TITLE
The problem of scanning the file with Chinese filename

### ISSUE THREAD

**Issue by N0body007** [hillu/go-yara#107]
Hello, I found a problem that go-yara can't scan the file with Chinese filename. I have tried the yara of new version,yara v4.2.2,on my windows 10 with Chinese char set machine,but when I use go-yara to scan the file with Chinese filename,such as 123.txt and 123测试.txt, it doesn't work. Could you help me out?

**Comment by hillu** [comment]
Sure. Could you please provide a small Go program that fails to scan your file using a dummy ruleset?

**Comment by hillu** [comment]
Great. What error are you getting when scanning the file that contains Chinese characters?

**Comment by N0body007** [comment]
The error is “could not open file” from the source code of yara. You can try the code above. When the filename is 123.txt, the result is nomal. But when the filename contains Chinese characters, it will get error.

**Comment by ozanh** [comment]
AFAIK, yara 4.1 does not support unicode file names. You can open the file with Go’s os.Open and provide file descriptor to go-yara to scan. I did it like this and solved it before.

**Comment by hillu** [comment]
@N0body007 what @ozanh said is correct. Go's internal filename representation is UTF-8 which works for your Chinese characters just fine. However, the filename is then passed as a C string to `yr_scanner_scan_file`, `yr_filemap_map`, `yr_filemap_map_ex` where it is finally passed as-is to the `CreateFileA` API. The A stands for ASCII and the UTF-8 multibyte representations of your non-ASCII characters will likely be misinterpreted … the file is simply not found.

I suggest the following change:
``` go
s.SetCallback(&m)
f, err := os.Open(targetFile)
if err != nil {
    fmt.Println("Open: err: ", err)
    return
}
defer f.Close()
if err := s.ScanFileDescriptor(f.Fd()); err != nil {
    fmt.Println("ScanFileDescriptor: err: ", err)
    return
} else {
    fmt.Printf("Matches: %+v", m)
}
```

**Comment by N0body007** [comment]
> AFAIK, yara 4.1 does not support unicode file names. You can open the file with Go’s os.Open and provide file descriptor to go-yara to scan. I did it like this and solved it before.

Thank you. Maybe now I understand where the reason is.

**Comment by N0body007** [comment]
> @N0body007 what @ozanh said is correct. Go's internal filename representation is UTF-8 which works for your Chinese characters just fine. However, the filename is then passed as a C string to `yr_scanner_scan_file`, `yr_filemap_map`, `yr_filemap_map_ex` where it is finally passed as-is to the `CreateFileA` API. The A stands for ASCII and the UTF-8 multibyte representations of your non-ASCII characters will likely be misinterpreted … the file is simply not found.
> 
> I suggest the following change:
> 
> ```go
> s.SetCallback(&m)
> f, err := os.Open(targetFile)
> if err != nil {
>     fmt.Println("Open: err: ", err)
>     return
> }
> defer f.Close()
> if err := s.ScanFileDescriptor(f.Fd()); err != nil {
>     fmt.Println("ScanFileDescriptor: err: ", err)
>     return
> } else {
>     fmt.Printf("Matches: %+v", m)
> }
> ```

Thank you. It really works. But I want to solve this problem by changing the source code of yara. Do you have any good suggestion?

**Comment by hillu** [comment]
@N0body007 There is an issue open in YARA: https://github.com/VirusTotal/yara/issues/1487.

A workaround similar to what I described above has been implemented in yara.c (the command line program), but there hasn't been any feedback whether this works or not. Note that currently, only the builds done with Visual Studio would be affected by this fix.

Or do you want to fix this in the libyara API?

**Comment by N0body007** [comment]
Yeah, I want to fix this in the libyara API.

**Comment by hillu** [comment]
> Yeah, I want to fix this in the libyara API.

OK, in that case we ought to continue the discussion in a new issue within the YARA project. Would you like to open an issue there?

**Comment by N0body007** [comment]
Hmm, I'll solve it by myself first, and then I'll open a new issue within the YARA project if I can't. Thank you.

**Comment by hillu** [comment]
> Hmm, I'll solve it by myself first, and then I'll open a new issue within the YARA project if I can't. Thank you.

My advice: The issue, at its core, is simple to fix: In `yr_filemap_map_ex`, replace the `CreateFileA` with `CreateFileW`. Assume that the string that got passed in is encoded as UTF-8; convert that to UTF-16 so it can be used by `CreateFileW`. I am pretty sure that a pull request that implements this change would be accepted.

But since this should really be discussed as a YARA issue (or pull request), so I am closing this issue.

**Comment by N0body007** [comment]
I get it. Thank you.
