### ISSUE TITLE
using go-yara with my own compiled yara library without crypto

### ISSUE THREAD

**Issue by Maimonator** [hillu/go-yara#108]
Hey there,
I compiled my own yara library using `--without-crypto` and I'd like to link it against `go-yara` but using `yara_no_pkg_config` adds the ldflag `-lcrypto` that isn't required by my yara library :( 
I was thinking on creating a `yara_no_crypto` tag to accommodate for that if that's sounds okay with you.

Also big thanks for supporting this library!

**Comment by hillu** [comment]
I suppose we could just remove the `-lcrypto` from `LDFLAGS` when `yara_no_pkg_config` is set.

For dynamic builds, this would not break anything.
For static builds, a user who needs OpenSSL support could add `-lcrypto` in the `go build` command line.

What do you think?

**Comment by Maimonator** [comment]
Actually sounds like a much better solution!

**Comment by hillu** [comment]
I got it.
