### ISSUE TITLE
Unable to define variable on AIX

### ISSUE THREAD

**Issue by asalih** [hillu/go-yara#130]
I am trying to run go-yara on AIX 7.2. When I try to create a scanner by defining a variable I get the "insufficient memory" error from NewScanner func. Do you know what's wrong here? Thank you. Ps: If the rule doesn't contain any external variable it is working.   

Error:
```
2023/09/29 12:10:29 Can not create scanner: insufficient memory
exit status 1
```
Environment: 
Platform: AIX 7.2 (PowerPC_POWER9)
go version: go1.20.7 aix/ppc64
YARA version: 4.3.1
go-yara version: 4.3.2

Executing below code with the following command:
` CGO_LDFLAGS="-L/yara-aix-build/lib" CGO_CFLAGS="-I/yara-aix-build/include" go run -tags "yara_no_pkg_config" main.go`

```golang
package main

import (
	"fmt"
	"log"

	"github.com/hillu/go-yara/v4"
)

const ruleStr = `rule aix_var_crash_test
{
    meta:
        description = "var crash"

    condition:
        test_var == "test"
}
`

func main() {
	compiler, err := yara.NewCompiler()
	if err != nil {
		log.Fatalf("Can not create compiler: %v", err)
	}

	err = compiler.DefineVariable("test_var", "")
	if err != nil {
		log.Fatalf("Can not define rule: %v", err)
	}

	// Add rules
	err = compiler.AddString(ruleStr, "")
	if err != nil {
		log.Fatalf("Can not add rule: %v", err)
	}

	// Compile rules
	rules, err := compiler.GetRules()
	if err != nil {
		log.Fatalf("Can not compile rule: %v", err)
	}

	scanner, err := yara.NewScanner(rules)
	if err != nil {
		log.Fatalf("Can not create scanner: %v\n", err)
	}

	var m yara.MatchRules
	err = scanner.SetCallback(&m).ScanFile("/path/to/scan.log")
	if err != nil {
		log.Fatalf("Can not scan file: %v \n", err)
	}

	fmt.Println("Match: %d", len(m))
}
```

**Comment by hillu** [comment]
Looks like a bug that occurs within libyara to me. Does the error go away if you do not call `compiler.DefineVariable` (and don't use a variable in your rule) ?

**Comment by asalih** [comment]
Yes it disappears. After troubleshooting the problem, I've finally figured out the problem, it was caused by the different behavior of the "calloc" function in AIX, @hillu Thank you for your response.

**Comment by hillu** [comment]
oh, great. Does `calloc`' on AIX behave differently in a way that is disturbed by Go's memory management? It might be worthwhile to report your finding as an issue to the YARA project.

**Comment by asalih** [comment]
Reported an [issue](https://github.com/VirusTotal/yara/issues/1980). This behavior comes from stdlib.h on AIX so I think there is no disturbance from Go memory management.
