### ISSUE TITLE
Scan a file in a streaming maner

### ISSUE THREAD

**Issue by rucciva** [hillu/go-yara#131]
Hello, is it possible to scan a file in a streaming manner? Maybe using memory block iterator?
If so then how can one implement it?

I'm exploring the idea of creating server that receive file to be scanned via http post request. Would be cool if we don't have to write the file to disk first to avoid disk io operation

**Comment by hillu** [comment]
Yes, the memory block iterator is the way to go. However, you'll have to store your file somewhere because the memory iterator may be opened after string scanning if conditions contain direct data accesses such the magic numbers checks using `uintXX()`.

**Comment by rucciva** [comment]
I see. So it's not fully possible to use stream operation then.

thanks for your kind respons
