### ISSUE TITLE
Encrypted rules?

### ISSUE THREAD

**Issue by RRancio** [hillu/go-yara#132]
hey its me again :V, does Go-Yara support the encripted rules using Yarac.exe encryption?

**Comment by hillu** [comment]
There is no encryption going on, the ruleset is just compiled.

Yes, go-yara supports loading compiled rulesets, see the `LoadRules` and `ReadRules` functions.

**Comment by hillu** [comment]
A practical problem with passing around commpiled rulesets is that they are tied to a specific YARA version.
