### ISSUE TITLE
linux编译yara出现错误

### ISSUE THREAD

**Issue by jumppppp** [hillu/go-yara#143]
# command-line-arguments
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status

**Comment by hillu** [comment]
Sorry, I don't speak Chinese.

**Comment by jumppppp** [comment]
ok, this question is resolved，flag value should be added during program compilation
