### ISSUE TITLE
Failing to compile with go-yara

### ISSUE THREAD

**Issue by icernn03** [hillu/go-yara#147]
Hi,
I'm new to GoLang and have been experimenting with the `go-yara` package. I'm encountering an error that I've been unable to resolve. I'm reaching out here in hopes of finding a solution.

**Environment**:
- GOVERSION: go1.22.2
- GOARCH: arm64
- CGO_ENABLED=0
- YARA version: 4.5.0
- go-yara version: v4.3.2
- OS: MacOS M1

```go
package main

import (
	"github.com/hillu/go-yara/v4"
	"github.com/rs/zerolog/log"
)

func main() {
	_, err := yara.NewCompiler()
	if err != nil {
		log.Print("Error Initializing Yara Compiler: ", err)
	}
}
```
when running the code
```bash
go run *.go
```
gives the following error
```bash
# command-line-arguments
./main.go:9:17: undefined: yara.NewCompiler
```
I followed [this fix](https://github.com/hillu/go-yara/issues/111#issuecomment-1478639046) too but with no avail.
The package is installed and `Gopls` reports no issue in `VSCode` and I am able to navigate to definitions.

**Comment by hillu** [comment]
I am not sure if `go run` sets `CGO_ENABLED`. Please try building a binary like so:
``` console
go build .
```
If that doesn't work, try setting the environment variable `CGO_ENABLED` to `1`.

**Comment by icernn03** [comment]
the issue was because I had `CGO_ENABLED=0` set. Got it fixed by installing `yara` from source using following  options
```bash
export CGO_CFLAGS="-I${YARA_SRC}/libyara/include"
export CGO_LDFLAGS="-L${YARA_SRC}/libyara/.libs"
```
Now I am able to run the program successfully in MacOS. However cross compiling for linux fails with the some errors

```bash
GOOS=linux GOARCH=amd64 go build -tags yara_static -ldflags="-extldflags='-static' -s -w" main.go
```
with CGO_ENABLED=1 give this error
```bash
# runtime/cgo
linux_syscall.c:67:13: error: call to undeclared function 'setresgid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: call to undeclared function 'setresuid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
```
and with CGO_ENABLED=0 falls back to same `undefined` error

Can you please help me understand the issue, 
Thank you so much, really appreciate your help.

**Comment by hillu** [comment]
In addition to setting `GOOS`, `GOARCH`, `CGO_ENABLED`, you'll also need to set `CC`

**Comment by icernn03** [comment]
I have installed following cross-compiler toolchains
```bash
brew install FiloSottile/musl-cross/musl-cross
brew install mingw-w64
```
tried to build
```bash
CC=x86_64-linux-musl-gcc CGO_ENABLED=1 CXX="x86_64-linux-musl-g++" GOOS=linux GOARCH=amd64 go build -trimpath -tags yara_static -ldflags="-extldflags='-static' -s -w" .
```
got the error
```
/usr/local/go/pkg/tool/darwin_arm64/link: running x86_64-linux-musl-gcc failed: exit status 1
/opt/homebrew/Cellar/musl-cross/0.9.9_2/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /var/folders/gw/j8qm0vvs3mzdttfr3gd_tsv40000gn/T/go-link-2563072701/000002.o: in function `_cgo_e4084b5c9b87_Cfunc__yr_compiler_add_fd':
compiler.cgo2.c:(.text+0x75): undefined reference to `yr_compiler_add_fd'
/opt/homebrew/Cellar/musl-cross/0.9.9_2/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /var/folders/gw/j8qm0vvs3mzdttfr3gd_tsv40000gn/T/go-link-2563072701/000002.o: in fu
....
/opt/homebrew/Cellar/musl-cross/0.9.9_2/libexec/bin/../lib/gcc/x86_64-linux-musl/9.2.0/../../../../x86_64-linux-musl/bin/ld: /var/folders/gw/j8qm0vvs3mzdttfr3gd_tsv40000gn/T/go-link-2563072701/000011.o: in function `_cgo_e4084b5c9b87_Cfunc_yr_scanner_set_timeout':
scanner.cgo2.c:(.text+0x569): undefined reference to `yr_scanner_set_timeout'
collect2: error: ld returned 1 exit status
```
also tried to follow the [guide](https://github.com/hillu/go-yara/blob/master/README.cross-building.md) and couldn't figure out the following env
```
YARA_BUILD_LINUX_MUSL
PREFIX_LINUX_MUSL
```

**Comment by icernn03** [comment]
Please bear with me, I am completely new to this. Thank you for your support

**Comment by hillu** [comment]
> Please bear with me, I am completely new to this. Thank you for your support

Don't worry. You are pasting meaningful error messages which does help.

The last error messages you posted mean that everything up till the linking stage has worked, it's just the linker that seems to have found _libyara.a_. Is it the correct _libyara.a_? Adding some flags increasing verbosity to `-extldflags` might help.

**Comment by hillu** [comment]
> also tried to follow the [guide](https://github.com/hillu/go-yara/blob/master/README.cross-building.md) and couldn't figure out the following env

I have just updated the document:

> For the examples below, YARA is built out-of-tree, i.e. the build
artifacts are placed into a separate directory referred to by the
`YARA_BUILD_*` shell variables. `YARA_SRC` refers to the YARA source
directory. The `PREFIX_*` refer to target directory for the `make
install` step.

Is this clearer?

**Comment by icernn03** [comment]
yes, it makes more sense now. Thank you.
Now I understand I need to first compile Yara to the target platform then my Go application
```bash
( cd ${YARA_BUILD_LINUX_MUSL} && \
 CC=x86_64-linux-musl-gcc ${YARA_SRC}/configure --prefix=${PREFIX_LINUX_MUSL} --host=x86_64-linux-musl)
 make -C ${YARA_BUILD_LINUX_MUSL} install
 ```
 I had to add `--host=x86_64-linux-musl` for `./configure`  to run successfully. However `make install` command still fails with missing header error
 ```
 /Library/Developer/CommandLineTools/usr/bin/make  install-am
  CC       libyara/la-filemap.lo
/Path/To/Src/yara-4.5.0/libyara/filemap.c:162:10: fatal error: linux/magic.h: No such file or directory
  162 | #include <linux/magic.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [libyara/la-filemap.lo] Error 1
make: *** [install] Error 2
```
I could not figure how to provide Linux headers to the compiler. I am assuming cross-compiler should be handling this if I have everything configured correctly. Have you any idea what could be misconfigured at this stage?

**Comment by icernn03** [comment]
I have managed to successfully compile now. I am really thank full for your assistance.

The cross-compiler [filosottile/musl-cross/musl-cross](https://github.com/FiloSottile/homebrew-musl-cross) has the headers under the directory `opt/homebrew/Cellar/musl-cross/0.9.9_2/libexec/`

To fix the missing library issue I downloaded [magic.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/magic.h) file and added it to the following folders inside that directory
```
aarch64-linux-musl/include/linux/
x86_64-linux-musl//include/linux/
include/linux/
```

Then ran Go build command successfully
```bash
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-linux-musl-gcc CXX=x86_64-linux-musl-g++ PKG_CONFIG_PATH=${PREFIX_LINUX_MUSL}/lib/pkgconfig go build -ldflags '-extldflags "-static"' -tags yara_static -o app-linux-amd64
```
Trying to build for Windows now 😊

**Comment by kmahyyg** [comment]
Just in case someone met the same problem here:

for now, in Debian bullseye, all dependencies I found you should install is:
```
apt install gcc-mingw-w64-x86-64 build-essential nano vim pkg-config libyara-dev git zlib1g-dev libbz2-dev libmagic-dev autoconf libtool curl ca-certificates libjansson-dev flex bison libzstd-dev libssl-dev musl-tools sudo -y
```

If you met the error below while compiling against musl-c:

snipped build error:
```
user@buildhost $ make -C ${YARA_BUILD_LINUX_MUSL} install
make: Entering directory '/opt/buildtargets/yara/musl_linux_amd64'
make  install-am
make[1]: Entering directory '/opt/buildtargets/yara/musl_linux_amd64'
  CC       libyara/la-filemap.lo
/root/softsrcs/yara-4.3.2/libyara/filemap.c:162:10: fatal error: linux/magic.h: No such file or directory
  162 | #include <linux/magic.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2127: libyara/la-filemap.lo] Error 1
make[1]: Leaving directory '/opt/buildtargets/yara/musl_linux_amd64'
make: *** [Makefile:3056: install] Error 2
make: Leaving directory '/opt/buildtargets/yara/musl_linux_amd64'
```

try:

```
( cd ${YARA_BUILD_LINUX_MUSL} && \
  ${YARA_SRC}/configure CC=musl-gcc --prefix=${PROJ_PREFIX_LINUX_MUSL} CFLAGS="-I/usr/include" CPPFLAGS="-I/usr/include")
make -C ${YARA_BUILD_LINUX_MUSL} install
```
