### ISSUE TITLE
yararule.ScanFile, can not scan filepath which contains chinese, may be other language has the same

### ISSUE THREAD

**Issue by binlmmhc** [hillu/go-yara#148]
![image](https://github.com/hillu/go-yara/assets/25096151/1f2ea147-501b-45a6-8889-cb28c672d7ff)

code below, use github.com/hillu/go-yara/v4 v4.3.2
![image](https://github.com/hillu/go-yara/assets/25096151/84d37548-3527-47d1-bfae-1719e1676c08)

**Comment by hillu** [comment]
Please have a look at the `ScanFile` documentation:
``` go
// Note that the filename is passed as-is to the YARA library and may
// not be processed in a sensible way. It is recommended to avoid this
// function and to obtain an os.File handle f using os.Open() and use
// ScanFileDescriptor(f.Fd()) instead.
```
The note is there exactly for string encoding reasons.

**Comment by binlmmhc** [comment]
copy that, thank you
