### ISSUE TITLE
Defining the same variable twice results in incorrect behaviour

### ISSUE THREAD

**Issue by CapacitorSet** [hillu/go-yara#25]
I found that if I define the same variable twice in the compiler, scanning gives incorrect results.

Here's a minimal testcase:

```go
package main

import (
	"fmt"
	"github.com/hillu/go-yara"
)

func errcheck(err error) { if err != nil { panic(err) } }

func main() {
	c, err := yara.NewCompiler()
	errcheck(err)
	err = c.DefineVariable("category", "")
	errcheck(err)
	err = c.DefineVariable("category", "")
	errcheck(err)
	err = c.AddString(`rule category_is_empty { condition: category == ""}`, "")
	errcheck(err)
	r, err := c.GetRules()
	errcheck(err)
	r.DefineVariable("category", "http")
	z, err := r.ScanMem([]byte{}, 0, 0)
	fmt.Printf("%#v\n", z)
}
```

One would expect that the rule `category_is_empty` wouldn't be matched, since `category` was defined to be equal to `"http"`. However, the rule *does* get matched.

If you remove the second definition, the code works as intended.

**Comment by hillu** [comment]
This is a bug in YARA itself.

**Comment by CapacitorSet** [comment]
Fixed upstream, closing this. Thank you for the quick response!
