### ISSUE TITLE
Import 'github.com/hillu/go-yara/internal/callbackdata" makes forking harder

### ISSUE THREAD

**Issue by plusvic** [hillu/go-yara#31]
When someone clones this repository the path `github.com/hillu/go-yara/internal/callbackdata` imported from `utils.go` causes the following error:
```
util.go:10:2: use of internal package not allowed
```
As the path contains `internal` it can only be imported from code inside the same module (ie: `github.com/hillu/go-yara`) the cloned repo has a different path and can't use this import path.

All users cloning this repository for experimentation will be faced with this error and may think that the code in the original repository is broken.

**Comment by hillu** [comment]
Argh, I should have seen that one coming. Do you see any solution that does not add an external dependency and that does not move the callback-related code back into the main package?

**Comment by plusvic** [comment]
I can't find a solution that doesn't involve having an external dependency. What's your worry about the external dependency?

**Comment by plusvic** [comment]
Yep, I support the idea of keeping it as self-contained as possible.
