### ISSUE TITLE
(*yara.Rules).Destroy() Memory Leak

### ISSUE THREAD

**Issue by Codehardt** [hillu/go-yara#33]
Hi hillu,

It seems that the `(*yara.Rules).Destroy()` function does not free all the memory allocated in C.

I wrote an example that reproduces the problem:

```golang
package main

import (
	"fmt"
	"os"
	"runtime"
	"strconv"
	"time"

	yara "github.com/hillu/go-yara"
)

const YaraRule = `rule MemoryLeak_%d {
strings:
	$s1 = "memory"
	$s2 = "leak"
condition:
	1 of them
}`

var variables = map[string]interface{}{
	"filename":  "",
	"filepath":  "",
	"filetype":  "",
	"extension": "",
}

func memoryLeak(i int64) {
	defer runtime.GC()
	r, err := yara.Compile(fmt.Sprintf(YaraRule, i), variables)
	if err != nil {
		panic(err)
	}
	defer r.Destroy()
	if _, err := r.ScanMem([]byte(fmt.Sprintf("memory leak %d", i)), 0, time.Second); err != nil {
		panic(err)
	}
}

func main() {
	n, err := strconv.ParseInt(os.Args[1], 10, 64)
	if err != nil {
		panic(err)
	}
	var i int64
	for ; i < n; i++ {
		memoryLeak(i)
	}
	time.Sleep(time.Second)
}
```

This program compiles rule by rule and destroys the compiled rule before initializing the next one. If `Destroy()` would work correctly, the memory usage for `n=1` should be approximately the same as for `n=10000`.

Here is an program that uses the above compiled program to measure the memory usage peek:

```golang
package main

import (
	"fmt"
	"os/exec"
	"syscall"
)

func main() {
	for _, n := range []int64{
		1, 10, 100, 1000,
	} {
		cmd := exec.Command("./memoryleak", fmt.Sprint(n))
		if err := cmd.Run(); err != nil {
			panic(err)
		}
		kb := cmd.ProcessState.SysUsage().(*syscall.Rusage).Maxrss / 1024
		fmt.Printf("%.4d: %.5d KB\n", n, kb)
	}
}
```

This produces the following output on macOS:

```
0001: 02612 KB
0010: 04704 KB
0100: 06156 KB
1000: 06872 KB
```

Do you know, weather this is a memory leak or not? I tried the same with a similar program that uses `strings.Contains(...)` instead of YARA to exclude that this is a Golang problem:

```golang
package main

import (
	"fmt"
	"os"
	"runtime"
	"strconv"
	"strings"
	"time"
)

const ContainsString = "No memory leak %d"

func noMemoryLeak(i int64) {
	defer runtime.GC()
	if !strings.Contains(fmt.Sprintf(ContainsString, i), fmt.Sprintf("leak %d", i)) {
		panic("assertion error")
	}
}

func main() {
	n, err := strconv.ParseInt(os.Args[1], 10, 64)
	if err != nil {
		panic(err)
	}
	var i int64
	for ; i < n; i++ {
		noMemoryLeak(i)
	}
	time.Sleep(time.Second)
}
```

and the measurements were:
```
0001: 01328 KB
0010: 01480 KB
0100: 01488 KB
1000: 01484 KB
```

Kind Regards,

Marcel Gebhardt

**Comment by hillu** [comment]
Assuming that the memroy leaks happens in Go land, you should be able to measure memory allocations at finer granularity using `runtime.ReadMemStats`.

**Comment by hillu** [comment]
@Codehardt Does the memory leak persist with latest master as of af9139bcbb5913bc0f015ca3b99805beec962a9a?

**Comment by hillu** [comment]
@Codehardt ping?

**Comment by Codehardt** [comment]
The memory leak still persists with [af9139b](https://github.com/hillu/go-yara/commit/af9139bcbb5913bc0f015ca3b99805beec962a9a), but it seems to improve the memory usage a bit.

> Assuming that the memroy leaks happens in Go land, you should be able to measure memory allocations at finer granularity using runtime.ReadMemStats.

This was my first approach, but I couldn't notice any memory leaks with Golang's GC.

Maybe there is no memory leak. I don't know how accurate the memory stats are, which are reported by the OS.

**Comment by Tasssadar** [comment]
Note: You have to call `debug.FreeOSMemory()` instead of `runtime.GC()` because just GC does not shrink the RSS.

I believe this is caused by how yara uses Thread Local Storage. Try running the same tests with `GOMAXPROCS=1` env variable set, the problem disappears, and if you set `GOMAXPROCS=1024` it is amplified.

Yara saves some data into TLS on each thread it runs on, and with Go, it's gonna be many different threads. Locking the scanning thread using `runtime.LockOSThread()` helps too.

I tried to replicate the same situation in  C, and it happens there too if you scan on multiple threads and keep them all alive.

**Comment by plusvic** [comment]
@Tasssadar made a good point, but I think it's not related to TLS, as recent YARA versions don't store as much data in TLS as it used to do. I think it's probably related to how heap allocators work.

I experienced a similar issue in the past and I found that most heap allocators, including the one used by libc, keep freed heap blocks in a list so they can be re-used by further calls to malloc. These blocks are freed from the heap standpoint, but not from the OS standpoint, they are still consuming virtual memory. The list of freed blocks is kept in a per-thread basis, so blocks freed by one thread won't be re-used by another thread. This is not a problem in C programs where you call YARA from a limited number of threads, but in golang you can't control which particular thread is calling YARA, so you may end up having a lot of heap blocks that YARA already freed but the heap allocator is holding in those per-thread lists just waiting for someone to call malloc again. The more threads you have the more noticeable is this problem. My solution was using `runtime.LockOSThread()` to force the goroutine that was calling YARA to run always from the same OS thread.
