### ISSUE TITLE
Instructions to build statically linked Linux binaries

### ISSUE THREAD

**Issue by botherder** [hillu/go-yara#35]
I'm trying to build a statically linked Linux binary using on Go 1.11:

`GOOS=linux GOARCH=amd64 go build --ldflags '-s -w -extldflags "-static"' -o agent`

But I'm having some difficulties. I have compiled Yara from the sources with `--without-crypto`, but I get the following errors:

```/home/user/.gvm/gos/go1.11/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-968020938/000011.o: in function `unixDlOpen':
/home/user/.gvm/pkgsets/go1.11/global/pkg/mod/github.com/mattn/go-sqlite3@v1.9.0/sqlite3-binding.c:37945: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000019.o: in function `mygetgrouplist':
/home/user/.gvm/gos/go1.11/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000018.o: in function `mygetgrgid_r':
/home/user/.gvm/gos/go1.11/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000018.o: in function `mygetgrnam_r':
/home/user/.gvm/gos/go1.11/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000018.o: in function `mygetpwnam_r':
/home/user/.gvm/gos/go1.11/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000018.o: in function `mygetpwuid_r':
/home/user/.gvm/gos/go1.11/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-968020938/000016.o: in function `_cgo_18049202ccd9_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:49: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: i386 architecture of input file `/tmp/go-link-968020938/000000.o' is incompatible with i386:x86-64 output
/usr/bin/ld: //usr/local/lib/libyara.a(math.o): in function `string_entropy':
math.c:(.text+0xea7): undefined reference to `log2'
/usr/bin/ld: //usr/local/lib/libyara.a(math.o): in function `data_entropy':
math.c:(.text+0x1126): undefined reference to `log2'
```

**Comment by hillu** [comment]
`log2` requires the math function library `libm` to be linked.

You may want to consider using a different libc when building completely static binaries. (Those warnings about `getpwnam_r` etc. are unfortunately very real.) I have found libmusl to be a good choice so far. Have a look at [SPYRE](https://github.com/DCSO/spyre)'s build system for inspiration on how to do a static build.

**Comment by botherder** [comment]
Thanks. I added a `-lm` to `-extldflags` and it seems to work. I was worried the other warnings, including the go-sqlite3 one, would break it somehow, but it seems to be working fine. Just out of curiosity, you're not specifying any custom LDFLAGS other than `-static` in your SPYRE Makefile, how are you achieving a static build?
Also, what particular advantage do you find from using musl-gcc instead? Seems like regular gcc builds it fine too.

**Comment by hillu** [comment]
The `-static` switch gets passed to gcc (which acts as the linker), this causes static libraries (`libFOO.a`) to be preferred over dynamic libraries (`libFOO.so`).
musl-gcc is basically a gcc wrapper that uses a different configuration which causes musl-libc to be used instead of the standard GNU libc. I do not use glibc because it cannot be used to build entirely statically linked binaries. This of course means that libyara, OpenSSL and possibly other C libraries need to be built using musl-libc instead of glibc, too.

**Comment by botherder** [comment]
Thanks. I'll give it a try with musl as well.
