### ISSUE TITLE
Cross-compiling for Darwin or FreeBSD fails because of build constraints

### ISSUE THREAD

**Issue by botherder** [hillu/go-yara#36]
While cross-compiling from a Debian dev machine to other platforms, building for Darwin and FreeBSD raises this issue instead:

```
go build github.com/hillu/go-yara/internal/callbackdata: build constraints exclude all Go files in $GOPATH/pkg/mod/github.com/hillu/go-yara@v1.0.9/internal/callbackdata
```

I've not been able to triage the issue entirely, although it sounds like it could be related to this? https://github.com/golang/go/issues/24068

**Comment by botherder** [comment]
Nevermind, my mistake.

**Comment by hillu** [comment]
What kind of C cross-compiler setup are you using for FreeBSD and Darwin targets?
