### ISSUE TITLE
Can't import module

### ISSUE THREAD

**Issue by altsab** [hillu/go-yara#38]
Can you try to compile this rules? I get an error `unknown module "magic"`, and also `undefined identifier "filepath"`
```yara
import "magic"

rule EXE_cloaked_as_TXT {
	meta:
		description = "Executable with TXT extension"
		license = "https://creativecommons.org/licenses/by-nc/4.0/"
		author = "Florian Roth"
	condition:
		uint16(0) == 0x5a4d 					// Executable
		and magic.mime_type() matches /\.txt$/is   // TXT extension (case insensitive)
}

rule Cloaked_RAR_File {
	meta:
		description = "RAR file cloaked by a different extension"
		license = "https://creativecommons.org/licenses/by-nc/4.0/"
		author = "Florian Roth"
	condition:
		uint32be(0) == 0x52617221							// RAR File Magic Header
		and not magic.mime_type() matches /(rarnew.dat|\.rar)$/is	// not the .RAR extension
		and not filepath contains "Recycle" 				// not a deleted RAR file in recycler
}
```

I installed yara with all the flags needed, and `file` library is present in my system (Fedora XFCE 28)

**Comment by altsab** [comment]
As for external variables like `filepath` I found out that yara-python can pass external variables to `match` method like this:
```python
matches = rules.match('/foo/bar/my_file',
  externals= {'var1': 'some other string', 'var2': 100})
``` 
Is it possible to provide similar functionality? To be able to define external variables for each scan.

**Comment by hillu** [comment]
@altsab go-yara can also pass external variables -- using `(*Compiler).DefineVariable()`. The missing import happens because the libyara library you are using has been built without support for libmagic. You'll either need to rebuild the C library or rewrite the rule. (I am quite surprised to learn that @Neo23x0 is using the `magic` feature in YARA rules.)

**Comment by altsab** [comment]
Yep, the thing is that I rebuilt it several times with all needed flags :thinking: 
Probably it's something to do with my system.

**Comment by hillu** [comment]
@altsab If you are using libyara-dev from current Debian or Ubuntu stable, you can just use that -- provided you pass the correct `yara3.x` build flag.

**Comment by hillu** [comment]
@altsab Please let me know if there's anything left unclear.
