### ISSUE TITLE
Can seem to build static linked binaries

### ISSUE THREAD

**Issue by scudette** [hillu/go-yara#40]
Not sure if this is supported but the documentation suggests that it should be possible:
```
The build tag yara_static can be used to tell the Go toolchain to run pkg-config with the --static switch.
```

Apparently this is not enough:
```
mic@elite:~/go/src/github.com/hillu/go-yara$ go build -tags yara_static  _examples/simple-yara/simple-yara.go 
mic@elite:~/go/src/github.com/hillu/go-yara$ ldd simple-yara 
        linux-vdso.so.1 (0x00007fffa8162000)
        libyara.so.3 => /usr/local/lib/libyara.so.3 (0x00007f24916c3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f24914a4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f24910b3000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f2490c3b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f249089d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f249192c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2490699000)
```

Should I be able to build without having to ship the shared object?

**Comment by hillu** [comment]
Hi Michael,

as far as I know, there is no way to specify the required external linker flags in `#cgo` pragmas, therefore I have updated the documentation.

**Comment by scudette** [comment]
Thanks for updating the docs. That linker flag will actually make a fully static binary but this is not really going to be very portable (modern systems can not run fully static binaries - see http://blog.rekall-forensic.com/2018/01/elf-hacking-with-rekall.html for a fully description.). 

What we really need is a statically linked libyara but not a fully static binary - it still needs to dynamically link to system libraries. Obviously we also dont want to change the entire build system for our binary just to include a minor library in it. There is no way we can ship a shared object as well with our single binary product either - so we need yara to be built into the binary itself.

I actually got it working now by simply building the yara library into the library itself (see https://github.com/Velocidex/go-yara). Its a bit hacky but means that users dont need to worry about building and linking flags and having libraries installed on the system. This is a similar idea to the python binding https://github.com/scudette/rekall-yara so it works really well. This also just works with windows build as well so users dont need to worry about installing libyara first.

Thanks for looking into this and thanks for an awesome project!

**Comment by hillu** [comment]
Thank you for pointing to your ELF hacking article, an interesting read! :-)

For Go-based projects that are linked with C libraries (and ltherefore need libc) such as [spyre](https://github.com/DCSO/spyre) and previous other non-public projects, I have used libmusl, an alternative libc that can be linked statically, so I can just pass `-ldflags=-extldflags="-static"` to the _go_ tool.

If you just want to link a few dependencies statically, you could make sure that those dependencies only get built as static libraries (`configure ... --disable-shared` should do the trick), so there'd be no need for patching around in those external libraries' source code...

I just tried mixing `#cgo ... LDFLAGS:` with `#cgo ... pkg-config`, but that does not seem to work either. I suppose that the best way is setting the `CGO_LDFLAGS` environment variable from an external build system such as a Makefile. If you still need to do a mix of static and dynamic linking, something like this might work:
```.make
TARGET: export CGO_LDFLAGS=--push-state -static $(shell pkg-config --static --libs yara) --pop-state
```
