### ISSUE TITLE
C.YR_CONFIG_MAX_MATCH_DATA

### ISSUE THREAD

**Issue by wangbokun** [hillu/go-yara#42]
Hi， 
go install -tags no_pkg_config github.com/hillu/go-yara

error msg is：

../../github.com/hillu/go-yara/config_yara38.go:12:39: could not determine kind of name for C.YR_CONFIG_MAX_MATCH_DATA

**Comment by hillu** [comment]
This constant was introduced in YARA 3.8. Please use the appropriate tag for the YARA version, (probably `yara3.7`) as specified in the README.

**Comment by hillu** [comment]
@wangbokun Were you able to fix your problem?

**Comment by hillu** [comment]
@wangbokun ping?

**Comment by hillu** [comment]
Closing the issue since original reporter has not provided any feedback.
