### ISSUE TITLE
Meta variables with duplicate name are lost

### ISSUE THREAD

**Issue by Tasssadar** [hillu/go-yara#44]
It is common to add hashes to test rules on in the meta variables like so:
```yara
rule test
{
    meta:
        // The files that should match this rule. It will be tested against these.
        hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        hash = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    condition:
        true
}
```

The current API loses the first `hash`, because the result is a map keyed by the variable name.

Possible fix, which will put `[]interface{}` into the `metas map[string]interface{}` map:
```diff
diff --git a/rule.go b/rule.go
index e0b7e7d..ef0966c 100644
--- a/rule.go
+++ b/rule.go
@@ -132,15 +132,30 @@ func (r *Rule) Metas() (metas map[string]interface{}) {
        for _, m := range mptrs {
                var id, str *C.char
                C.meta_get(m, &id, &str)
+               goId := C.GoString(id)
+
+               var val interface{}
                switch m._type {
                case C.META_TYPE_NULL:
-                       metas[C.GoString(id)] = nil
+                       val = nil
                case C.META_TYPE_STRING:
-                       metas[C.GoString(id)] = C.GoString(str)
+                       val = C.GoString(str)
                case C.META_TYPE_INTEGER:
-                       metas[C.GoString(id)] = int(m.integer)
+                       val = int(m.integer)
                case C.META_TYPE_BOOLEAN:
-                       metas[C.GoString(id)] = m.integer != 0
+                       val = m.integer != 0
+               default:
+                       continue
+               }
+
+               if oldval, prs := metas[goId]; prs {
+                       if sl, ok := oldval.([]interface{}); ok {
+                               metas[goId] = append(sl, val)
+                       } else {
+                               metas[goId] = []interface{}{oldval, val}
+                       }
+               } else {
+                       metas[goId] = val
                }
        }
        return
```

I'm not too happy with it though, too many `interface{}` :/

**Comment by hillu** [comment]
Hi @Tasssadar,

thank you. I wasn't aware of this problem. I think you're right about an overuse of `interface{}`...
What do you think about adding a separate method? Let's call it `Metas2` that returns a `map[string][]interface{}` where the individual `interface{}` values would be guaranteed to be a nil, string, integer, or boolean value just like with the existing `Metas` method.

**Comment by hillu** [comment]
For what it's worth, the Python bindings show the same behavior:
```
#!/usr/bin/python3
import pprint
import yara

rs = yara.compile(source="""
rule test
{
    meta:
        hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        hash = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    condition:
        true
}
""")
ms = rs.match(data="")
pprint.pprint(ms[0].meta)
```

**Comment by Tasssadar** [comment]
Here's a pull request on the python implementation. They basically added a second Meta() method that can return lists: https://github.com/VirusTotal/yara-python/pull/74

Perhaps add an api that would return `map[string]MetaEntry`, and MetaEntry would have nice methods to work with:
- IsString, IsInt, IsBool, IsList....
- `String() string`, `Int() int` (panic when the type is wrong?)

It's a little bit unfortunate that each of the variables in list can have a different type. If we'd restrict this artificialy in go-yara, we could have nice methods like:
- `Strings() []string`, `Ints() []int`...

**Comment by hillu** [comment]
I don*t like the combination `IsString() bool` / `String() string` (with panic). You end up having more explicit library code compared to passing back `interface{}`s with a documented selection of 3 or 4 types. And the burden of checking for the correct type is still left with the caller -- without allowing for language features such as type switches.

**Comment by hillu** [comment]
@Tasssadar I'd like to put the named identifier and `interface{}` value into a new `Meta` type and have a `MetaList` method that returns a list of `Meta`s, in the same order that the meta variables were defined (and how the YARA C API returns them). What do you think?

**Comment by Tasssadar** [comment]
That sounds good to me, probably better than to return `[]interface{}` for each meta variable name.

**Comment by Tasssadar** [comment]
Hello, any progress on this? I think the solution with MetaList/MetaMap looks pretty good, could you merge it to master please?

**Comment by hillu** [comment]
Oh, yeah, I had totally forgotten about that...
