### ISSUE TITLE
Completely wipes .yar file && "Could not open file"

### ISSUE THREAD

**Issue by TheRedSpy15** [hillu/go-yara#49]
So, I made a **very** rough draft of a program. And I have the following code:
```
func printMatches(m []yara.MatchRule, err error) {
	if err == nil {
		if len(m) > 0 {
			for _, match := range m {
				log.Printf("- [%s] %s ", match.Namespace, match.Rule)
			}
		} else {
			log.Print("no matches.")
		}
	} else {
		panic(err.Error())
	}
}

func main() {
	compiler, err := yara.NewCompiler()
	if err != nil {
		panic(err.Error())
	}
	file, err := os.Create("/home/user/Documents/Golang/code/Go-Away-AV/ShadowTech.yar")
	if err != nil {
		panic(err.Error())
	}
	compiler.AddFile(file, "Infinity.yar")
	scanner, err := compiler.GetRules()
	if err != nil {
		panic(err.Error())
	}
	scanned, err := scanner.ScanFile("/home/user/Documents/SecurityUSB - Backup/Windows/Anti malware", 0, 0)
	printMatches(scanned, err)
}
```
However, It for some reason completely deletes everything in the .yar file, while keeping the file itself. It is **also** throwing the error: "could not open file" at the 'ScanFile()' section

**Comment by hillu** [comment]
The .yar file is being wiped because you open it using [os.Create](https://golang.org/pkg/os/#Create). Use [os.Open](https://golang.org/pkg/os/#Open) instead.

**Comment by TheRedSpy15** [comment]
@hillu that fixes the clearing of the .yar file, but I still get the fail to open error

**Comment by hillu** [comment]
The "could not open file" error corresponds to the `ERROR_COULD_NOT_OPEN_FILE` C constant. This is returned if either the `open` or the `fstat` syscall inside `yr_filemap_map_ex` or `yr_filemap_map_fd` fails. This must have something to do with the filename or the file's permissions.

**Comment by TheRedSpy15** [comment]
It was this filename for anyone with a similar problem. There was whitespace in the path

**Comment by hillu** [comment]
I have not seen that opening files with whitespace in their path is a problem -- neither in the libyara C API nor in the Go code that is wrapped around that C API. The most sensible explanation to me is that you mistyped the name somewhere. (Feel free to provide a reproducer that includes an archive with the exact filenames if you think this is not the case.)
