### ISSUE TITLE
Assertion `match_offset + match_length <= callback_args->data_size' failed.

### ISSUE THREAD

**Issue by reijin90** [hillu/go-yara#53]
I ran some fuzz testing and uncovered this assertion fail:
`scan.c:521: int _yr_scan_match_callback(const uint8_t *, int32_t, int, void *): Assertion match_offset + match_length <= callback_args->data_size failed.`

This is technically libyara related, but I felt like posting here too.

Fuzzer code:
```
package main

// commit as of file creation (13.02.2019): 4cc0204f70e49688c0f42637dda8326344c64325
// https://github.com/hillu/go-yara/tree/4cc0204f70e49688c0f42637dda8326344c64325
import "github.com/hillu/go-yara"

//we need import c!

import "C"

//replace original main with dummy main()
func main(){}

//export Fuzz
func Fuzz(data []byte){
	c, err := yara.NewCompiler()
	if err != nil {
		return
        }
        defer c.Destroy()
        err = c.AddString(string(data[:]), "")
        if err != nil {
                return
        }
	r, err := c.GetRules()
	if err != nil {
		return
	}
        _, _ = r.ScanFile("testfile", 0, 0)
}
```
Testfile is a PNG file. 

Crasher file is attached. [crash-0de6903a06f42da60003232dd862790a7bd5ade3.zip](https://github.com/hillu/go-yara/files/3004320/crash-0de6903a06f42da60003232dd862790a7bd5ade3.zip)

**Comment by hillu** [comment]
Hi @reijin90,
While doing some spring cleaning, I stumbled about the issue you filed just over two years ago and I can report that a minimized variant of the ruleset you reported still leads to an abort in YARA 4.1.0 (see below). Did you ever report it to the YARA project?

rule.yar:
``` yara
rule r18 
{  strings:
    $a = { 0D 5? [3430-] [3430-] C3}
  condition:
    $a
}
```
min.png:
``` xxd
00000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR
00000010: 0000 08dc 0000 0512 0802 0000 0057 21e9  .............W!.
00000020: f000 0020 0049 4441 5478 9cec dddf 6b6b  ... .IDATx....kk
00000030: 5b9e 20f6 e5c3 217f 4006 d2a7 237b b0a9  [. ...!.@...#{..
```
``` console
$ yara --version
4.1.0
$ yara rule.yar min.png
warning: rule "r18" in rule.yar(3): string "$a" may slow down scanning
yara: scan.c:654: _yr_scan_match_callback: Assertion `match_offset + match_length <= callback_args->data_size' failed.
Aborted
```

**Comment by hillu** [comment]
Has this been published?

**Comment by reijin90** [comment]
> Has this been published?

check your email inbox :)

**Comment by hillu** [comment]
since the original issue can now be tracked with the YARA project, I'm closing the issue here.
