### ISSUE TITLE
Docker Deployment and Cgo Cfunc_string_matches

### ISSUE THREAD

**Issue by PimmyTrousers** [hillu/go-yara#55]
# Problem overview
I have been attempting to deploy a web service in Go within a docker container (ubuntu 19.04) that accept a file and returns the names for each rule that matches. When testing this on my local machine (macOS) with yara 3.11 and yarac 3.11 I am able to scan the wannaCry sample `[ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa](https://www.virustotal.com/gui/file/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa/detection)`. Although when I go deploy this service within the docker container I get the following errors. 

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f pc=0xcd3e97]

runtime stack:
runtime.throw(0xf1dee4, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 61 [syscall, locked to thread]:
runtime.cgocall(0xcd3e60, 0xc000344d20, 0x1)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000344cf0 sp=0xc000344cb8 pc=0x40b96b
github.com/hillu/go-yara._Cfunc_string_matches(0x7fb6c544ec05, 0x0, 0xc0004c9bfc)
	_cgo_gotypes.go:1121 +0x45 fp=0xc000344d20 sp=0xc000344cf0 pc=0xb07415
github.com/hillu/go-yara.(*String).Matches(0xc000344e48, 0x0, 0x0, 0x0)
	/go/src/github.com/hillu/go-yara/rule.go:225 +0x6b fp=0xc000344db8 sp=0xc000344d20 pc=0xb0c2ab
github.com/hillu/go-yara.(*Rule).getMatchStrings(0xc0000a8ce0, 0x0, 0x0, 0x0)
	/go/src/github.com/hillu/go-yara/rule.go:244 +0x2c2 fp=0xc000344ec0 sp=0xc000344db8 pc=0xb0c722
github.com/hillu/go-yara.(*MatchRules).RuleMatching(0xc000324220, 0xc0000a8ce0, 0xc000324220, 0x7fb6ec1219f0, 0xc000324220)
	/go/src/github.com/hillu/go-yara/rules_callback.go:151 +0x224 fp=0xc000345020 sp=0xc000344ec0 pc=0xb0e3e4
github.com/hillu/go-yara.scanCallbackFunc(0x1, 0x7fb6c3d6916d, 0x21bb7e0, 0xf395a8)
	/go/src/github.com/hillu/go-yara/rules_callback.go:90 +0x220 fp=0xc000345100 sp=0xc000345020 pc=0xb0ddf0
github.com/hillu/go-yara._cgoexpwrap_08a63f7e5a95_scanCallbackFunc(0x7fb600000001, 0x7fb6c3d6916d, 0x21bb7e0, 0x0)
	_cgo_gotypes.go:1621 +0x3d fp=0xc000345130 sp=0xc000345100 pc=0xb08aad
runtime.call32(0x0, 0x7fb6cdffa3f0, 0x7fb6cdffa480, 0x20)
	/usr/local/go/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000345160 sp=0xc000345130 pc=0x461f3b
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:314 +0x1b7 fp=0xc000345248 sp=0xc000345160 pc=0x40bd17
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xc1 fp=0xc0003452b0 sp=0xc000345248 pc=0x40bac1
runtime.cgocallback_gofunc(0x40b98f, 0xcd40b0, 0xc000345340, 0xc000345330)
	/usr/local/go/src/runtime/asm_amd64.s:793 +0x9b fp=0xc0003452d0 sp=0xc0003452b0 pc=0x46350b
runtime.asmcgocall(0xcd40b0, 0xc000345340)
	/usr/local/go/src/runtime/asm_amd64.s:640 +0x42 fp=0xc0003452d8 sp=0xc0003452d0 pc=0x4633a2
runtime.cgocall(0xcd40b0, 0xc000345340, 0x10279e1)
	/usr/local/go/src/runtime/cgocall.go:131 +0x7f fp=0xc000345310 sp=0xc0003452d8 pc=0x40b98f
github.com/hillu/go-yara._Cfunc_yr_rules_scan_mem(0x7fb6d4000eb0, 0xc001c5d19a, 0x35a000, 0x1, 0xcd3790, 0x21bb7e0, 0x0, 0x0)
	_cgo_gotypes.go:1524 +0x4d fp=0xc000345340 sp=0xc000345310 pc=0xb0855d
github.com/hillu/go-yara.(*Rules).ScanMemWithCallback.func1(0xc0000a8960, 0xc001c5d19a, 0xc001c5d19a, 0x35a000, 0xd4a656, 0x1, 0x21bb7e0, 0x0, 0x7523cf)
	/go/src/github.com/hillu/go-yara/rules.go:91 +0xfc fp=0xc0003453a0 sp=0xc000345340 pc=0xb1099c
github.com/hillu/go-yara.(*Rules).ScanMemWithCallback(0xc0000a8960, 0xc001c5d19a, 0x35a000, 0xd4a656, 0x1, 0x0, 0xdc17a0, 0xc000324220, 0x0, 0x0)
	/go/src/github.com/hillu/go-yara/rules.go:91 +0x1b7 fp=0xc000345488 sp=0xc0003453a0 pc=0xb0cb27
github.com/hillu/go-yara.(*Rules).ScanMem(...)
	/go/src/github.com/hillu/go-yara/rules.go:68
github.secureserver.net/threat/util/yara.(*Rules).ScanBuffer(0xc0001559e0, 0x1054b20, 0xc000022080, 0xc001c5d19a, 0x35a000, 0xd4a656, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.secureserver.net/threat/util/yara/yara.go:84 +0x184 fp=0xc000345660 sp=0xc000345488 pc=0xb142d4
project/classification.(*Plugin).classifySamples(0xc0002b6c80, 0x1054b20, 0xc000022080, 0xc0001f5000, 0xc00014c660, 0x0, 0x17, 0xc000575960)
	/go/src/project/classification/classification.go:176 +0x1dd fp=0xc000345800 sp=0xc000345660 pc=0xb16b0d
```

This stack trace basically shows that we're taking in a sample, attempting to classify it, using ScanBuffer as the mechanism for scanning and returning the matching rules. The top function within the stack trace points to `github.com/hillu/go-yara._Cfunc_string_matches` so I've been trying to figure out how this function could cause issues within a docker a container but nowhere else. 

As for the ruleset, I have been using a relatively large [ruleset](https://github.com/Yara-Rules/rules) for testing and when using rules that just check for the PE header or the Cannot Run in DOS mode string, there are no errors so this could also be the source of error here. 

With regards to how I am installing Yara in the docker container, following is a snippet for how I am installing yara on the host that contains the go built application as well 
```
# steps required to install Yara and remove the source files
RUN git clone https://github.com/VirusTotal/yara.git /tmp/yara
WORKDIR ${YARA_SRC_PATH}
RUN \
    apt update && \
    apt install automake libtool make pkg-config libyara-dev libc-dev -y && \
    ./bootstrap.sh && \
    ./configure && \
    make && \
    make install && \
    rm -rf ${YARA_SRC_PATH}
```

## Things I have tried so far
- compiling the rules with yarac and compiling them within the web service
  - had no effect, still caused issues with the wannacry sample
- Check if its an issue within the docker container or something that would be an issue on my host machine as well
  - Its not an issue on the host machine, so that means something is missing within the docker container or how yara interacts with the ubuntu base image
- Checks yara versions
  - Yara and Yarac in the deploy container are both running version 3.11
- Adding libc-dev and file-dev as those pacakges are added in the official yara docker image
  - Does not seem to fix the issue

**Comment by hillu** [comment]
Can you reproduce the crash every time, given the same sample and ruleset?

**Comment by PimmyTrousers** [comment]
yes I can reproduce it every time and interesting so, its exactly this everytime `[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f pc=0xcd3e97]`

**Comment by hillu** [comment]
Great! Can you strip down the application you deploy using Docker into something I could use for trying to reproduce the issue? Also, I'd need access to the sample. (Putting it into an encrypted ZIP file and attaching it to the issue might work.)

**Comment by PimmyTrousers** [comment]
Yup ill create a recreatable dockerfile and post it here!

**Comment by PimmyTrousers** [comment]
Hello again! Created a repo to replicate the issue I'm seeing. If you have any questions lemme know https://github.com/PimmyTrousers/DockerYaraMock

**Comment by hillu** [comment]
Thanks.

**Comment by botherder** [comment]
FWIW, I've been having the same issue (contacted @hillu over email about it).
I am not running the Yara scanner in a docker container, and it also crashes in the same place with a rather large ruleset.

**Comment by PimmyTrousers** [comment]
@hillu I believe I have a fix for this. https://github.com/hillu/go-yara/pull/57

**Comment by hillu** [comment]
@PimmyTrousers I believe that your build setup might be to blame for the crash. I noticed that you install `libyara-dev` which pulls in the `libyara3` shared library package. If `libyara-dev` is replaced by the packages that are needed to build the Debian `yara` package, the problem goes away.

There are two other things that my PR (https://github.com/PimmyTrousers/DockerYaraMock/pull/1) does:

1. Run `ldconfig` after `make install` otherwise yarac cannot be run.
2. Run configure with the same parameters as is done in the Debian `yara` package; otherwise the ruleset cannot be compiled because it relies on modules that have to be enable explicitly.

Both steps indicate that `libyara.so.3` from the distribution was used previously.

**Comment by hillu** [comment]
@PimmyTrousers Ping? Can I close this issue?

**Comment by PimmyTrousers** [comment]
Yes we can close the issue. You were right. You're fix was correct :) Thanks for the fix!

**Comment by botherder** [comment]
@hillu Is there any way to avoid this issue, without either compiling directly on the production server or using a statically linked binary?
Would compiling with the same version as the libyara3 installed on the production server work?

**Comment by hillu** [comment]
@botherder Compiling with the same libyara3 version should work.
