### ISSUE TITLE
LoadRules fails with any Yara rule

### ISSUE THREAD

**Issue by botherder** [hillu/go-yara#6]
I'm testing your library, and at this attempt:

    rules, err := yara.LoadRules(rules_path)

    if err != nil {
        fmt.Println("Something failed loading rules!");
        panic(err)
    }

I always get:

```
Something failed loading rules!
panic: invalid file

goroutine 1 [running]:
panic(0x4a79a0, 0xc420012310)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
main.main()
	/whatever/whatever/main.go:19 +0x5a7
exit status 2
```

I am using Yara 3.5.0 and I have tested with pretty much whatever rule.
Am I doing something wrong?

**Comment by hillu** [comment]
* Nex:

> I'm testing your library, and at this attempt:
>
> ` rules, err := yara.LoadRules(rules_path)
>
> if err != nil {
>     fmt.Println("Something failed loading rules!");
>     panic(err)
> }`
>
> I always get:
>
> `Something failed loading rules!
> panic: invalid file

Are you trying to load rules in source form? The `LoadRules` function is
intended for loading compiled rulesets (just like `yr_rules_load` from
libyara).

In order to process source files, you'd need to instantiate a Compiler,
add strings or file contents (using the `AddString` and `AddFile`
methods, respectively) and generate a `Rules` object using the
`GetRules` method that you can use for scanning.

Cheers,
-Hilko

**Comment by botherder** [comment]
I have done the Compiler + AddFile + GetRules combo originally, but reading the documentation of LoadRules it sounded as if that function would have wrapped that whole process. The documentation says the function only expects a filename and namespace.

**Comment by hillu** [comment]
* Nex:

> I have done the Compiler + AddFile + GetRules combo originally, but
> reading the documentation of LoadRules it sounded as if that function
> would have wrapped that whole process. The documentation says the
> function only expects a filename and namespace.

Oh. I suppose I'll have to update the documentation, then.

Sorry about that.

Cheers,
-Hilko

**Comment by hillu** [comment]
Mhm. The bit of documentation so far says:
<pre>// LoadRules retrieves a compiled ruleset from filename.</pre>
To me it seems that this seems about as clear as it gets. Do you have a suggestion for improvement?

**Comment by botherder** [comment]
I was mostly referring to the C API documentation to be honest:
`Load rules from the file specified by filename. Returns one of the following error codes:`
I'm sorry if I'm being dumb, but I'm not familiar with Yara API other than Python's and perhaps I'm misunderstanding the documentation.

I guess that both documentations speak of loading rules from a file in a compiled format rather than source then. That was not clear to me. (tbh, I think the original Yara C API doc isn't that clear either)

Sorry for bothering.

**Comment by hillu** [comment]
No worries. :-) Let's see if we can improve bits of the original YARA documentation, then.
