### ISSUE TITLE
Need to update bindings and API for upcoming YARA 4

### ISSUE THREAD

**Issue by cblichmann** [hillu/go-yara#65]
A lot of the `yr_?_foreach()` macros that are used in the C interface have changed in recent YARA commits expecting an additional `YR_SCAN_CONTEXT` parameter.

The same is true for the callback functions given to the `yr_?_scan_mem()` functions:

```c
int callback_function(
    YR_SCAN_CONTEXT* context,
    int message,
    void* message_data,
    void* user_data);
```

As it is, go-yara does not compile with https://github.com/VirusTotal/yara/commit/6c91c5dbcf4f723edf7e1b7af7c3c6567a57f987.

**Comment by hillu** [comment]
Don't worry, I'm on it. :-)

**Comment by cblichmann** [comment]
I also looked into this yesterday. I had some success with https://github.com/cblichmann/go-yara/commit/ae329b3da20632c0c55c406f91b87e5290bd8308. Tried to minimize the necessary changes.

Let me know if this is useful. Happy to prepare a PR.

**Comment by hillu** [comment]
Oh, I am sorry for not being clearer–I have got a branch that seems to be working and that I hadn't published to Github yet.

My v4-specific changes do look pretty close to yours. As this is going to break API compatibility with existing code (like YARA itself does), I'll also be getting rid of the different YARA 3.x-specific cases and build flags.

**Comment by hillu** [comment]
In the meantime I have pushed changes that make go-yara work with yara 4.0. No tag yet because I am still working on some cleanups that will introduce more breaking changes.
