### ISSUE TITLE
FEATURE: Build Rules from Rule

### ISSUE THREAD

**Issue by Xumeiquer** [hillu/go-yara#66]
It would be useful to have a way to convert or get a Rules object from a Rule object or a set of Rule objects.

Something like this:
```go
func LoadRule(rule *Rule) (*Rules, error)
```
In the same line, adding Rule objects to a already Rules object, like this:
```go
func (r *Rules) AddRule(rule *Rule) error 
```

**Comment by hillu** [comment]
I'm afraid that this is not going to be possible due to the way YARA works internally.

**Comment by Xumeiquer** [comment]
Such a shame though.
