### ISSUE TITLE
Compiling for Windows instructions

### ISSUE THREAD

**Issue by mcastilho** [hillu/go-yara#7]
I have been struggling to get this compiled for windows using MinGW.

It would be good to have more instructions on how to proper compile the Yara project and generate libyara for windows 32 and 64bit. Even thought Yara has the Visual Studio solutions and I can easily generate libyara32.lib and libyara64.lib.... Not sure if these are compatible with MinGW and CGO

And how to have this package use these libs with CGO.

**Comment by chennqqi** [comment]
Both msys and msys2 work correctly.
Compile libyara by mingw-gcc.

**Comment by mcastilho** [comment]
@chennqqi 

This is what I did to compile Windows 64-bit libyara.a. I did all compilation in a Ubuntu docker image using MinGW-w64

```
> docker run -t -i ubuntu:latest /bin/bash
```

And these are the exact commands I performed.

```
apt-get update
apt-get install build-essential git
apt-get install gcc-multilib gcc-mingw-w64 autoconf automake libtool libjansson-dev libmagic-dev libssl-dev
git clone --depth=50 https://github.com/VirusTotal/yara.git VirusTotal/yara
export CONFIGFLAGS=--host=x86_64-w64-mingw32
export CC=gcc
cd VirusTotal/yara
./bootstrap.sh
unset CC
./configure $CONFIGFLAGS
make
cd libyara/.libs
file libyara.a
```

Worked like a charm.... I was able to incorporate this libyara.a into this go-yara project

I had to do one modification and create a cgo_windows.go file with the following CGO instructions. I also copied the .H headers into a new ```./include``` folder and the windows lib into a new ```./lib``` folder

```
// +build windows

package yara

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo amd64 LDFLAGS: -L${SRCDIR}/lib -lyara64
#cgo 386 LDFLAGS: -L${SRCDIR}/lib -lyara32
*/
import "C"
...
```

and modified the old cgo.go file to:

```
// +build !windows

package yara

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo LDFLAGS: -lyara
*/
import "C"
```

Now I can build from my Sierra macOS both Darwin and Windows executables of my project that is using go-yara package with the following command to target Windows:

```
CC=/usr/local/Cellar/mingw-w64/4.0.6/bin/x86_64-w64-mingw32-gcc \
LD=/usr/local/Cellar/mingw-w64/4.0.6/bin/x86_64-w64-mingw32-ld \
  CGO_ENABLED=1 \
  GOOS=windows \
  CGO_CFLAGS=-I/usr/local/Cellar/mingw-w64/4.0.6/x86_64-w64-mingw32/include \
  CGO_LDFLAGS=-L/usr/local/Cellar/mingw-w64/4.0.6/x86_64-w64-mingw32/lib \
  go build --ldflags '-extldflags "-static"' .
```

And voilà !!!  Works like a charm.... I have tested the binary on Windows 10 x64 and works very well... without any dependencies. 

It took a while to figure it out. Hopefully this will help other people... Maybe we should move this instructions to the Readme ? Feedback ?

**Comment by hillu** [comment]
@mcastilho So you are still using the libyara32 and libyara64 generated through the VS project? Do you think that it would make sense to add a build tag, say `vs`?
```
#cgo windows,vs,i386 LDFLAGS: -lyara32
#cgo windows,vs,amd64 LDFLAGS: -lyara64
```

**Comment by mcastilho** [comment]
No. I am not using the VIsual studio output. I don't think is compatible. I am using the binaries produced by the compilation under Ubunto using MingGW

**Comment by hillu** [comment]
In that case, the resulting libraries should simply have the name `libyara.a` (without a `32` or `64` prefix), shouldn't they? Unless you have renamed them, of course.

**Comment by mcastilho** [comment]
Yes. I did rename them

**Comment by hillu** [comment]
Would you mind looking at my updated build/install instructions and tell me if they work for you?

**Comment by chennqqi** [comment]
@mcastilho I did that under windows and linux.

1. build static libyara and install to a `libyara_path`
`sudo yum install mingw32-gcc`
`
./configure --build=i686-w64-mingw32  --without-crypto --disable-shared --disable-dependency-tracking --disable-magic --disable-cuckoo   --without-crypto
`
make && sudo make install prefix=/usr/i686-w64-mingw32/
`
2. build go-yara and link `libyara_path`
i386-windows:
`
CC=i686-w64-mingw32-gcc   CGO_ENABLED=1   GOOS=windows GOARCH=386   CGO_CFLAGS=-I/usr/i686-w64-mingw32/include   CGO_LDFLAGS='-L/usr/i686-w64-mingw32/lib -lyara'   go install --ldflags '-extldflags "-static"' github.com/hillu/go-yara
`
x64-linux:
`
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CGO_CFLAGS=-I/usr/include CGO_LDFLAGS='-L/opt/x86_64/lib -lyara -lm'   go install --ldflags '-extldflags "-static"' github.com/chennqqi/go-yara
`
3. build your app with link `libyara_path`
x64-linux:
`
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CGO_LDFLAGS='-L/opt/x86_64/lib -L/usr/lib64' go build --ldflags '-s -w -extldflags "-static -lm"'  YOURAPPPATH
`
...other environment.

May this help you. Happy chinese new year!

**Comment by hillu** [comment]
@chennqqi Neither `-I/usr/i686-w64-mingw32/include` nor `-L/usr/i686-w64-mingw32/lib` should be necessary, the MinGW compiler includes those search paths by default.

**Comment by valinorsystems** [comment]
I got error when I built go-yara:
could not determine kind of name for C.ERROR_INSUFICIENT MEMORY


I tried building with all of instructions, in all cases - this error. Tried on Debian and Ubuntu - same thing.
go version - 1.8

**Comment by hillu** [comment]
oh, awesome, Fixing typos in YARA after 3.5 breaks the API...

**Comment by hillu** [comment]
Closing the issue since everything discussed here has been resolved.

**Comment by Jacob-Dong** [comment]
> x86_64-w64-mingw32-gcc



> @chennqqi
> 
> This is what I did to compile Windows 64-bit libyara.a. I did all compilation in a Ubuntu docker image using MinGW-w64
> 
> ```
> > docker run -t -i ubuntu:latest /bin/bash
> ```
> 
> And these are the exact commands I performed.
> 
> ```
> apt-get update
> apt-get install build-essential git
> apt-get install gcc-multilib gcc-mingw-w64 autoconf automake libtool libjansson-dev libmagic-dev libssl-dev
> git clone --depth=50 https://github.com/VirusTotal/yara.git VirusTotal/yara
> export CONFIGFLAGS=--host=x86_64-w64-mingw32
> export CC=gcc
> cd VirusTotal/yara
> ./bootstrap.sh
> unset CC
> ./configure $CONFIGFLAGS
> make
> cd libyara/.libs
> file libyara.a
> ```
> 
> Worked like a charm.... I was able to incorporate this libyara.a into this go-yara project
> 
> I had to do one modification and create a cgo_windows.go file with the following CGO instructions. I also copied the .H headers into a new `./include` folder and the windows lib into a new `./lib` folder
> 
> ```
> // +build windows
> 
> package yara
> 
> /*
> #cgo CFLAGS: -I${SRCDIR}/include
> #cgo amd64 LDFLAGS: -L${SRCDIR}/lib -lyara64
> #cgo 386 LDFLAGS: -L${SRCDIR}/lib -lyara32
> */
> import "C"
> ...
> ```
> 
> and modified the old cgo.go file to:
> 
> ```
> // +build !windows
> 
> package yara
> 
> /*
> #cgo CFLAGS: -I${SRCDIR}/include
> #cgo LDFLAGS: -lyara
> */
> import "C"
> ```
> 
> Now I can build from my Sierra macOS both Darwin and Windows executables of my project that is using go-yara package with the following command to target Windows:
> 
> ```
> CC=/usr/local/Cellar/mingw-w64/4.0.6/bin/x86_64-w64-mingw32-gcc \
> LD=/usr/local/Cellar/mingw-w64/4.0.6/bin/x86_64-w64-mingw32-ld \
>   CGO_ENABLED=1 \
>   GOOS=windows \
>   CGO_CFLAGS=-I/usr/local/Cellar/mingw-w64/4.0.6/x86_64-w64-mingw32/include \
>   CGO_LDFLAGS=-L/usr/local/Cellar/mingw-w64/4.0.6/x86_64-w64-mingw32/lib \
>   go build --ldflags '-extldflags "-static"' .
> ```
> 
> And voilà !!! Works like a charm.... I have tested the binary on Windows 10 x64 and works very well... without any dependencies.
> 
> It took a while to figure it out. Hopefully this will help other people... Maybe we should move this instructions to the Readme ? Feedback ?

I followed the above steps, but returned the error " /usr/bin/x86_64-w64-mingw32-ld: unable to find - lyara64 ". Could you help me solve it ?

**Comment by hillu** [comment]
@Jacob-Dong The error
```
/usr/bin/x86_64-w64-mingw32-ld: unable to find - lyara64
```
tells you that the linker that is invoked for linking the final program or library does not find `libyate64.a`, `libyara64.so` or `libyara64.dll` in the search path for libraries (parameter `-L`, usually specified via `LDFLAGS` environment variable.)

If you built YARA from sources, it's most likely that `libyara.a` and `libyara.so.*` was generated, so the `-lyara64` parameter would be wrong.

**Comment by Jacob-Dong** [comment]
> lls you that the linker that is invoked for linking the final program or library does not find `libyate64.a`, `libyara64.so` or `libyara64.dll` in the search path for libraries (parameter `-L`, usually specified via `LDFLAGS` environment variable.)
> 
> If you built YARA from sources, it's most likely that `libyara.a` and `libyara.so.*` was generated, so the

Thanks for answering. Actually as you said, so I modified the " -lyara64 " of cgo_windows.go to "-lyara", then the error disappered.
