### ISSUE TITLE
Go mod and V4 release

### ISSUE THREAD

**Issue by Kevintjeb** [hillu/go-yara#72]
Hi, 

Currently we want to use Go-Yara V4 in a Go Modules project. However, due to the go.mod in the master branch not having v4 in the file the tooling is fetching v1.3.0. It can't fetch v4.0.0 as this is disallowed (since the go.mod doesn't have v4, but the fallback to v0.0 or v1.x ..).

Could you bump the go.mod file to v4?

Thanks!

**Comment by hillu** [comment]
Oh, I see what's wrong. Trying to build any project that contains a `go.mod` file containing the line
```
require github.com/hillu/go-yara v4.0.0
```
results in an error message `require github.com/hillu/go-yara: version "v4.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4`.

Awesome.

Is there any other way to deal with this stupidity than to move everything to a `v4/` subdirectory? Trying to make sense of the documentation is quite frustrating…

**Comment by kvandenbroek** [comment]
Following the docs we should have a V4 dir with the V4 changes. However, we could also change the go mod file in the master to include V4 in the header. This way whenever you go get it, it will take the v4 tags. (If there are breaking changes, you shouldn't do this though)

You can simply create a V4 folder, only including the new Go mod and Go sum (With the V4 header)

**Comment by Kevintjeb** [comment]
Woops, that was my other account ! :D 

I fiddled around a bit, and this is how it also works without the V4 folder

https://github.com/Kevintjeb/go-yara/releases

**Comment by hillu** [comment]
@Kevintjeb You pointed me in the right direction. Changing the module name in the `go.mod` file in the root directory fixed things.

I have now tagged v4.0.2 (because I had burned v4.0.1 for <https://sum.golang.org/>. Oh well.

I am still quite frustrated about the mess that is Go Modules related documentation (no clear specification in sight anywhere…), but thank you very much for helping me fix this.
