### ISSUE TITLE
Using go-yara in Google Cloud Functions

### ISSUE THREAD

**Issue by Kevintjeb** [hillu/go-yara#73]
Hey!

We're trying to use go-yara in Google Cloud Functions. Currently it does not work due to pkg_config not being available in Google Cloud Functions

```
Build failed: # pkg-config --cflags -- yara
Package yara was not found in the pkg-config search path.
Perhaps you should add the directory containing `yara.pc'
to the PKG_CONFIG_PATH environment variable
No package 'yara' found
pkg-config: exit status 1
```

My guess is that we need to pre-compile Yara and ship it while deploying for it to work?
What do you think?

**Comment by hillu** [comment]
Yes, you'lll need to have YARA installed. I have not yet worked with GCF, so I don't know if you can just setup some package management (apt, rpm, whatever) to install a libyara-dev package.

**Comment by Kevintjeb** [comment]
Using the pre compiled binary in Google Cloud Functions doesn't seem to work. GCF does the `go build` process for you, and that invokes the go-yara build. This in turn goes to pkg-config, which can't find the yara.pc. If you include the yara.pc in your source, and expose the env variable in the GCF it still doesn't work.

My guess is that the env variables are included during the runtime of the function, not compile/build time. Therefore it won't work in any other possible way, as it's also not possible to instruct the build step in GCF. (Like using no-pkg-config build step in the readme).

Our solution would be to go and use Google Cloud Run, which is basically a product that accepts any docker container and gives you the same flexibility as GCF do.
