### ISSUE TITLE
Unbale to retrieve the latest version

### ISSUE THREAD

**Issue by Xumeiquer** [hillu/go-yara#74]
Hi, I am trying to get the latest version but it is impossible. I am using Go Modules so I am executing `go get -u=patch github.com/hillu/go-yara@v4.0.2` but I get an error:
```
go get github.com/hillu/go-yara@v4.0.2: github.com/hillu/go-yara@v4.0.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4 
```
According to the error it seems that the good values for the latest version are `v0` or `v1`. When forcing the the version to `v4` like `go get github.com/hillu/go-yara@v4` I get an error:
```
go get github.com/hillu/go-yara@v4: no matching versions for query "v4"
```
Finally, if I try to retrieve the latest I get an error regarding versions mismatching and than means the @latest is still go-yara v1.3.0.
```
go get github.com/hillu/go-yara@latest
# github.com/hillu/go-yara
../../../../pkg/mod/github.com/hillu/go-yara@v1.3.0/cgo.go:15:2: error: YARA version 3 required
#error YARA version 3 required
 ^
1 error generated. 
```

**Comment by Xumeiquer** [comment]
Need to add `/v4` on imports.

**Comment by hillu** [comment]
Ah, great; glad you figured that out. Seems like there might be room for improvement in the documentation.
