### ISSUE TITLE
Compiler Warnings/Errors not collected (anymore)

### ISSUE THREAD

**Issue by rhyselsmore** [hillu/go-yara#8]
Hi there,

It seems that a previously working behaviour, being the ability to pull warnings/errors from the compiler, no longer works.

## Replication

OSX 10.11.6

```
$ go version
go version go1.8 darwin/amd64
```

```
$ yara -v
yara 3.5.0
```

```
$ cd $GOPATH/src/github.com/hillu/go-yara && git rev-parse HEAD
f0a137cfb146d381a6cca4ba9797251bfc5b06f1
```

To observe this behaviour, run the following code:

```
package main

import (
	"fmt"

	"github.com/hillu/go-yara"
)

func main() {
	// Build a Yara Compiler
	compiler, err := yara.NewCompiler()
	if err != nil {
		panic(err)
	}

	// Add an obviously broken rule
	compiler.AddString("rule foo { bar }", "default")

	// Debug the Compiler Errors/Warnings
	fmt.Println(compiler.Errors)
	fmt.Println(compiler.Warnings)
}
```

### Output

```
$ go run main.go
[]
[]
```

## Investigation

I have found that `userData`, when checked at https://github.com/hillu/go-yara/blob/master/compiler.go#L30, is appearing as nil. I am not too familiar with how this should work to offer a fix.

**Comment by hillu** [comment]
Thank you for your analysis and the test case. The fix was rather easy. I must have left that nil check there when trying to figure out how to implement C callbacks without violating the more strict pointer passing rules introduced with Go 1.6.

**Comment by rhyselsmore** [comment]
Thank you so much. This is so much appreciated.

Please reach out if I can buy you a 6 pack of beer/a bottle of wine/a pizza for the fix.
