### ISSUE TITLE
Macos 11.0.1 Compiling Windows Yara

### ISSUE THREAD

**Issue by Aixic-Love** [hillu/go-yara#81]
`CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CGO_LDFLAGS="-L/usr/local/Cellar/yara/4.0.2/lib/ -lyara" CGO_CFLAGS="-I/usr/local/Cellar/yara/4.0.2/include" go install github.com/hillu/go-yara/v4`

![image](https://user-images.githubusercontent.com/50495439/102067751-84acb800-3e36-11eb-82e7-96444848ab81.png)
![image](https://user-images.githubusercontent.com/50495439/102067769-8b3b2f80-3e36-11eb-916b-7da91aa61804.png)

`CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CGO_LDFLAGS="-L/usr/local/Cellar/yara/4.0.2/lib/ -lyara" CGO_CFLAGS="-I/usr/local/Cellar/yara/4.0.2/include" go install -x github.com/hillu/go-yara/v4`

![image](https://user-images.githubusercontent.com/50495439/102067933-be7dbe80-3e36-11eb-9fa6-b4ec6d3d3bbf.png)

I need to run the yara plugin on windows cross-platform.

aaaa....... install yara ,Is used to test...
Because of the same error  :(

**Comment by hillu** [comment]
@Aixic-Love I can only guess what you are trying to tell me, please be somewhat more specific.

It seems that you'd like to cross-build go-yara for Windows but from the paths it looks like you are pointing the linker to MacOSX libraries that have been installed by the Homebrew package manager. This makes no sense -- you'll have to build _libyara_ for Windows, using pretty much the same steps as for cross-building Windows libraries on Linux described in README.cross-building.md.

**Comment by Aixic-Love** [comment]
I tried to use libyara of Linux to compile successfully

**Comment by Aixic-Love** [comment]
execution make install ....

![image](https://user-images.githubusercontent.com/50495439/102165858-9d64ae80-3ec6-11eb-817f-c25dd2bf33ab.png)
oh ...

**Comment by hillu** [comment]
The "multiple definitions" error is an error in YARA itself which only got resolved recently in https://github.com/VirusTotal/yara/pull/1416.

**Comment by Aixic-Love** [comment]
Can ignore it?

**Comment by Aixic-Love** [comment]
@hillu It's OK to compile the sample, but there is still an error in my project.
![image](https://user-images.githubusercontent.com/50495439/102168613-7f4d7d00-3ecb-11eb-8f27-c27d4a84d5b3.png)

**Comment by hillu** [comment]
Seems like you're using YARA from the master branch now where data structures have changed. Update go-yara to master, too, I fixed this recently in 3d95754ba628149cbd18d2e80939208b1bd82c5a.
