### ISSUE TITLE
build yara static

### ISSUE THREAD

**Issue by zhou88qiao** [hillu/go-yara#82]
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: cannot find -ldl
/bin/ld: cannot find -lcrypto
/bin/ld: cannot find -ldl
/bin/ld: cannot find -lz
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lm
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

**Comment by hillu** [comment]
What are you trying to achieve? This copy&pasted error message without context does not have any meaning to me, sorry.

**Comment by hillu** [comment]
ping?

**Comment by hillu** [comment]
Closing the issue due to inactivity.
