### ISSUE TITLE
support `warning as error`

### ISSUE THREAD

**Issue by virusdefender** [hillu/go-yara#84]
at now, the lib handles warning callback, but the warning message is not used

https://github.com/hillu/go-yara/blob/7cf0cc1935de2fc1262b2bb53eefb2bb97aa512c/compiler.go#L43

https://github.com/hillu/go-yara/blob/7cf0cc1935de2fc1262b2bb53eefb2bb97aa512c/compiler.go#L148

How to implement it?

 - add a new argument to `AddString`/`AddFile`, but it can break compatibility
 - add it as an option of compiler, like `c := NewCompiler()    c.WarningAsError = true`

**Comment by hillu** [comment]
Since the warnings are collected with the `Compiler` object, all information that is needed by user code is there.

Is this more than an aesthetic problem?

**Comment by virusdefender** [comment]
Maybe it's an aesthetic problem.

People may ignore the existence of warning without reading the source code, so it can cause some problem after a long time ( such as regex performance warning )

In yara tool, the warning message is printed to stdout, In yara-python, `error_on_warning =True` argument is supported.

**Comment by hillu** [comment]
The yara-python case is simpler since the underlying `YR_COMPILER` type (which go-yara encapsulates in `Compiler`) is hidden from the user altogether and the rules can only be compiled in one go.

On the other hand, you can pass strings to the `YR_COMPILER` object as long as the compiler itself does not raise a parsing (or other) error.

Here's an example.
``` go
func compileRules(rules []string) (*yara.Rules, error) {
    c, _ := yara.NewCompiler()
    for i, r := range rules {
        if err := c.AddString(r, ""); err != nil {
            return nil, fmt.Errorf("ruleset #%d contains errors", i)
        } else if len(c.Warnings) > 0 {
            return nil, fmt.Errorf("ruleset compiler raised warnings for ruleset #%d", i)
        }
    }
    return c.GetRules()
}
```

Does that help?

**Comment by virusdefender** [comment]
I know how to check the warning, this is just a discussion about the option.

We re-open it if other people think is necessary.
