### ISSUE TITLE
could not determine kind of name for C.ERROR_INSUFICIENT_MEMORY

### ISSUE THREAD

**Issue by jdrissel** [hillu/go-yara#9]
It appears that there is a typo in error.go...
	C.ERROR_INSUFICIENT_MEMORY:           "insufficient memory",
                    
should be
	C.ERROR_INSUFFICIENT_MEMORY:           "insufficient memory",

This does not make it work for me yet, but at least now I am getting errors that make some sense...

**Comment by hillu** [comment]
The typo was in previous versions of YARA -- and by not keeping the misspelled version of the constant around, the YARA public API was broken. See [YARA issue #623](https://github.com/VirusTotal/yara/pull/623)

**Comment by hillu** [comment]
@jdrissel [YARA PR #623](https://github.com/VirusTotal/yara/pull/623) has been merged. Since it appears that you were using a git snapshot of YARA anyhow, would you mind updating that and giving it another try? Thanks

**Comment by jdrissel** [comment]
Changes to the yara project fixed this.
