### ISSUE TITLE
Without restarting the program, repeated loading of some rules keeps increasing memory

### ISSUE THREAD

**Issue by eventian** [hillu/go-yara#90]
Go-Yara is used in my program. Now I want to reload a batch of rules according to the reload rule command I received without restarting the program. I use the command 'top' to monitor the proportion of memory, but after reloading, the memory has been increasing without being released.

**Comment by hillu** [comment]
My best guess is that the Go garbage collector does not collect the Rules object (which would cause `yr_rules_destroy` to be called), but without a reproducer, it is hard to tell.

Is the size of the memory leak similar to the size of the compiled ruleset?

**Comment by hillu** [comment]
Can you share some code sample that demonstrates the behavior?

**Comment by qtmee** [comment]
> Can you share some code sample that demonstrates the behavior?

是的，几乎相同

**Comment by qtmee** [comment]
> Can you share some code sample that demonstrates the behavior?

Yes, almost the same

**Comment by qtmee** [comment]
> My best guess is that the Go garbage collector does not collect the Rules object (which would cause `yr_rules_destroy` to be called), but without a reproducer, it is hard to tell.
> 
> Is the size of the memory leak similar to the size of the compiled ruleset?

Yes, almost the same

**Comment by qtmee** [comment]
> Can you share some code sample that demonstrates the behavior?
sample: https://github.com/qtmee/yara-memory-leak.git

Browser enter http://localhost:3000/i to simulate the upgrade command
![image](https://user-images.githubusercontent.com/52312713/123577712-f5ca2080-d806-11eb-9eb2-6373abe0ae90.png)

**Comment by qtmee** [comment]
> > Can you share some code sample that demonstrates the behavior?
> > sample: https://github.com/qtmee/yara-memory-leak.git
> 
> Browser enter http://localhost:3000/i to simulate the upgrade command
![image](https://user-images.githubusercontent.com/52312713/123577810-15614900-d807-11eb-828c-bb51c6c13655.png)

**Comment by qtmee** [comment]
> > > Can you share some code sample that demonstrates the behavior?
> > > sample: https://github.com/qtmee/yara-memory-leak.git
> > 
> > Browser enter http://localhost:3000/i to simulate the recreate command
> > ![image](https://user-images.githubusercontent.com/52312713/123577810-15614900-d807-11eb-828c-bb51c6c13655.png)

**Comment by qtmee** [comment]
> Can you share some code sample that demonstrates the behavior?

https://github.com/qtmee/yara-memory-leak.git

![image](https://user-images.githubusercontent.com/52312713/123577393-50af4800-d806-11eb-9db1-124e2d4e374d.png)

**Comment by qtmee** [comment]
> Can you share some code sample that demonstrates the behavior?

sample: https://github.com/qtmee/yara-memory-leak.git

Browser enter http://localhost:3000/i to simulate the recreate command
![image](https://user-images.githubusercontent.com/52312713/123579034-a5a08d80-d809-11eb-87d9-74488f463077.png)

**Comment by hillu** [comment]
Does adding `runtime.GC()` after replacing the Rules instance fix the problem for you?

How about explicitly calling `s.Rules.Destroy()` right before replacing it?

**Comment by qtmee** [comment]
> Does adding `runtime.GC()` after replacing the Rules instance fix the problem for you?
> 
> How about explicitly calling `s.Rules.Destroy()` right before replacing it?

Both approaches have been tried, and memory has not dropped

**Comment by hillu** [comment]
I have added a few endpoints to your sample in order to trigger GC and to log malloc statistics using the _malloc_stats(3)_ function. Here's what I have found:
This is the initial state (before any rules have been parsed):
```
Arena 0:
system bytes     =     135168
in use bytes     =       4752
Arena 1:
system bytes     =     135168
in use bytes     =       2896
Arena 2:
system bytes     =     135168
in use bytes     =       2896
Arena 3:
system bytes     =     135168
in use bytes     =       2896
Arena 4:
system bytes     =     135168
in use bytes     =       2896
Total (incl. mmap):
system bytes     =     675840
in use bytes     =      16336
max mmap regions =          0
max mmap bytes   =          0
```
It turns out that having YARA parse a ruleset even just once will considerably grow Arena 4:
```
Arena 4:
system bytes     =   16281600
in use bytes     =   15946016
```
Forcing GC will cause the "in use bytes" value to drop, but the "system bytes" value will stay at its previous level.
```
Arena 5:
system bytes     =   16281600
in use bytes     =      48112
```
Note that for some reason, Arena 4 is now called Arena 5, but the "system bytes" value stays the same. (I don't know enough about the GNU libc heap implementation to explain this.)

Parsing the ruleset multiple times without forcing a GC will cause the rulesets to be allocated to multiple arenas.

Also note that 45216 bytes have apparently not been freed. 

_malloc(3)_ keeps buffers around for subsequent reuse, that's a reason why the "system bytes" values are not dropped. What looks like a HUGE memory leak may still be a leak in the code but not as large as one would think. Most of the leak has something to do with GNU libc _malloc(3)_ implementation and probably fragmentation.

The Dgraph developers seem to have run into similar effects and their [solution](https://dgraph.io/blog/post/manual-memory-management-golang-jemalloc/) is to use jemalloc. One can override the default _malloc(3)_ implementation with jemalloc using `LD_PRELOAD` on Linux:
``` console
: ; LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 ./main
```
Of course this is not a proper solution but it may help you in the short term. I'll try to figure out how to fix this with the standard _malloc(3)_.

**Comment by qtmee** [comment]
> I have added a few endpoints to your sample in order to trigger GC and to log malloc statistics using the _malloc_stats(3)_ function. Here's what I have found:
> This is the initial state (before any rules have been parsed):
> 
> ```
> Arena 0:
> system bytes     =     135168
> in use bytes     =       4752
> Arena 1:
> system bytes     =     135168
> in use bytes     =       2896
> Arena 2:
> system bytes     =     135168
> in use bytes     =       2896
> Arena 3:
> system bytes     =     135168
> in use bytes     =       2896
> Arena 4:
> system bytes     =     135168
> in use bytes     =       2896
> Total (incl. mmap):
> system bytes     =     675840
> in use bytes     =      16336
> max mmap regions =          0
> max mmap bytes   =          0
> ```
> 
> It turns out that having YARA parse a ruleset even just once will considerably grow Arena 4:
> 
> ```
> Arena 4:
> system bytes     =   16281600
> in use bytes     =   15946016
> ```
> 
> Forcing GC will cause the "in use bytes" value to drop, but the "system bytes" value will stay at its previous level.
> 
> ```
> Arena 5:
> system bytes     =   16281600
> in use bytes     =      48112
> ```
> 
> Note that for some reason, Arena 4 is now called Arena 5, but the "system bytes" value stays the same. (I don't know enough about the GNU libc heap implementation to explain this.)
> 
> Parsing the ruleset multiple times without forcing a GC will cause the rulesets to be allocated to multiple arenas.
> 
> Also note that 45216 bytes have apparently not been freed.
> 
> _malloc(3)_ keeps buffers around for subsequent reuse, that's a reason why the "system bytes" values are not dropped. What looks like a HUGE memory leak may still be a leak in the code but not as large as one would think. Most of the leak has something to do with GNU libc _malloc(3)_ implementation and probably fragmentation.
> 
> The Dgraph developers seem to have run into similar effects and their [solution](https://dgraph.io/blog/post/manual-memory-management-golang-jemalloc/) is to use jemalloc. One can override the default _malloc(3)_ implementation with jemalloc using `LD_PRELOAD` on Linux:
> 
> ```
> : ; LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 ./main
> ```
> 
> Of course this is not a proper solution but it may help you in the short term. I'll try to figure out how to fix this with the standard _malloc(3)_.

Thank you very much for your answer. I will continue to pay attention to this problem and try the solution you have provided at present

**Comment by hillu** [comment]
I have taken a closer look at the various malloc tuning parameters documented in the GNU libc manual, but they don't seem to make any difference.

Rather than setting LD_PRELOAD, you can use a compiler build flag, though:
``` console
; go build -ldflags="-linkmode=external -extldflags=-ljemalloc"
```

**Comment by cooktian** [comment]
Do I modify the Go-Yara source code directly?  Change malloc used in CGO to je_calloc?  I have tried but failed. Could you help me to do it again? Thank you

**Comment by eventian** [comment]
This problem has been solved。There are no direct loading yara rules，the yara rules are precompiled, and the yara rules that have been precompiled are loaded when reloaded。

**Comment by eventian** [comment]
This problem has been solved。There are no direct loading yara rules，the yara rules are precompiled, and the yara rules that have been precompiled are loaded when reloaded。
