### ISSUE TITLE
Is it possible to get more verbose compiler errors?

### ISSUE THREAD

**Issue by FabFaeb** [hillu/go-yara#91]
Hi,

I am currently having to following problem: 
When I add a file with a syntax error to the yara compiler (i.e. c.AddFile(someFile, "someNamespace")), the resulting error does not give me any meta information about the location of the error in the file. This is especially problematic with large rule files. 
When I compile the same file with yarac (i.e. yarac /path/to/someFile /tmp/yara.out), the error is a lot more verbose: it shows the path to the faulty file as well as the line in the file and the relevant rulename. This makes locating and fixing the error a lot easier.

Example error from go-yara:
`syntax error, unexpected identifier, expecting '=' `
Example error from yarac:
`rule "my_rulename" in /path/to/someFile(123): syntax error, unexpected identifier, expecting '='`

Is it possible to get this more verbose error message in go-yara as well?

**Comment by hillu** [comment]
Warnings and error messages should be collected in `(Compiler).Warnings` and `(Compiler).Errors`, respectively.

**Comment by FabFaeb** [comment]
That works, thanks a lot!
