### ISSUE TITLE
windows goland support?

### ISSUE THREAD

**Issue by Kwansy98** [hillu/go-yara#94]
Can we import go-yara on windows 10 goland in the future? (Sorry for this stupid request but that will save us a lot of time :(

**Comment by hillu** [comment]
Since I am no Goland user, I have no clue on what would be necessary. Are there standard recipes for dealing with other libraries that have C-based dependencies?

**Comment by hillu** [comment]
@Kwansy98 ping?

**Comment by Kwansy98** [comment]
I am newbee on golang and i am not sure about that. maybe i should use vscode + go cli rather than goland and compile on cygwin or something, idk...
