### ISSUE TITLE
cbPool storage exhausted

### ISSUE THREAD

**Issue by lpendergrass** [hillu/go-yara#98]
Still seeing "cbPool storage exhausted" in 4.1.0 similar to #88. Haven't dug into cbPool but is there any particular limitation or resource constraint that can be reconfigured as a workaround?

% go list -m all | grep yara
github.com/hillu/go-yara/v4 v4.1.0

% yara --version
4.1.3

cbPool storage exhausted

goroutine 963 [running]:
github.com/hillu/go-yara/v4.(*cbPool).Put(0xc0001b60a0, {0x4183a40, 0xc000013350})
	/Users/user/go/pkg/mod/github.com/hillu/go-yara/v4@v4.1.0/cbpool.go:56 +0x158
github.com/hillu/go-yara/v4.(*Scanner).putCallbackData(0xc000013200)
	/Users/user/go/pkg/mod/github.com/hillu/go-yara/v4@v4.1.0/scanner.go:138 +0x12d
github.com/hillu/go-yara/v4.(*Scanner).ScanMem(0xc000013200, {0xc001358500, 0x4c9, 0x4ca})
	/Users/user/go/pkg/mod/github.com/hillu/go-yara/v4@v4.1.0/scanner.go:153 +0x5d
main.Scan({0xc00082c500, 0x9c}, 0x0, 0xc000832018)

**Comment by LancePendergrass** [comment]
I might not entirely understand here... but would hardcoding this at 256 cause any potential contraints elsewhere if scanning with a large number of rules?

https://github.com/hillu/go-yara/blob/master/util.go#L9

**Comment by ozanh** [comment]
Hi @LancePendergrass 
As I use the go-yara heavily, I had realized cbPool limit and took some actions to prevent crashes. Under normal circumstances, one cannot easily exceed the cbPool limit but I limit the number of yara scanner goroutines to `min(64, 2 * number of CPU)`. We use go-yara in thousands of machines around the world and I haven't been informed about any bug related to this.

**Comment by LancePendergrass** [comment]
Okay limiting to runtime.NumCPU() and leveraging a similar pattern to below seems to have worked. Thanks.

https://stackoverflow.com/a/25306241

**Comment by hillu** [comment]
@lpendergrass By default, YARA concurrency is limited to 32 threads. If you limit your program to that value, you still should not run out of cbpool values.

If anyone has a good suggestion how to document the limit (and what those panics actually mean: PRs are welcome, of course.

**Comment by ozanh** [comment]
@hillu After my quick text search in yara source code, I couldn't find a limit for yaralib concurrency. `YR_MAX_THREADS` or `ERROR_TOO_MANY_SCAN_THREADS` aren't applicable for the library, but are used in yara cli and sandbox folders. Let me know if I missed something and let me know if it can be added to go-yara doc as a concurrency best practice.

**Comment by hillu** [comment]
@ozanh You're right; the static scan thread limit went away in YARA 4.0 and `YR_MAX_THRERAD` serves no other purpose than API compatibility.

This means that for practical the number of concurrent YARA threads may be way higher than before – so perhaps it makes sense to be able to grow the callback data structure on demand.

**Comment by lpendergrass** [comment]
Dynamic growth of that cap sounds like the way to go but in lieu of that it might help to document it somewhere or indicate this in the exception message.

https://github.com/hillu/go-yara/blob/master/cbpool.go#L56

**Comment by hillu** [comment]
Sure. If somebody wants to take a shot at it, I'm open to PRs.

**Comment by hillu** [comment]
As of 309929481e1e5074241053571827951094ca7f50, dbPool has been replöaced with `cgo.Handle` (or an equivalent implementation that is used on older Go versions).

Closing this issue. Feel free to reopen if the issue comes up again.
